### ISSUE TITLE
Subtask: Compute map in format specified by get map/pixels

### ISSUE THREAD

**Issue by softgitron** [Cluster-ry/titeenipeli_25#63]
Subtask for #32

Create an algorithm that can compute map in get map/pixels format. At this point it is enough that unit tests do pass for the algorithm. No need to connect it yet to the rest of the application. Algorithm has following requirements:

- [x] Algorithm must produce 2 dimensional array that includes all player pixels.
- [x] In addition algorithm must take into account player's field of view so array will be field of view amount of larger compared to furthest player pixels.
- [x] Array must include other pixels that are in player's field of view.
- [x] Player spawn must be marked in.

See [OpenAPI specification](https://titeenipeli-koodaajille-2024.cluster2017.fi/) for exact details.
